### ISSUE TITLE
Question table column's width should be fixed size when rejudging

### ISSUE THREAD

**Issue by Chaoyuuu** [Judge-Girl/Judge-Girl-CMS#103]
![image](https://user-images.githubusercontent.com/41495987/119968518-2c323700-bfe0-11eb-8ac1-9da8d9b59b38.png)

![image](https://user-images.githubusercontent.com/41495987/119968769-626fb680-bfe0-11eb-8a27-3d75698e91f9.png)

**Comment by nyngwang** [comment]
Fixed in the linked PR.
