### ISSUE TITLE
Group Members' UI is gone

### ISSUE THREAD

**Issue by Chaoyuuu** [Judge-Girl/Judge-Girl-CMS#80]
- Fixed the ui problem
- the URL `/groups/{groupId}/students` should change to `/groups/{groupId}/members`

![image](https://user-images.githubusercontent.com/41495987/118250506-25cc9700-b4d9-11eb-8858-ac43de2a37a8.png)

**Comment by nyngwang** [comment]
I will resolve this in the PR following Dev/93
